export const product = [
    {
        id: 1,
        image: '../assets/img/product.jpg',
        name: 'abc',
        rate: 5,
        saleOff: 0,
        price: '120$',
        available: true,
    },
    {
        id: 1,
        image: '../assets/img/product.jpg',
        name: 'abc',
        rate: 5,
        saleOff: 0,
        price: '120$',
        available: true,
    },
    {
        id: 1,
        image: '../assets/img/product.jpg',
        name: 'abc',
        rate: 5,
        saleOff: 0,
        price: '120$',
        available: true,
    },
    {
        id: 1,
        image: '../assets/img/product.jpg',
        name: 'abc',
        rate: 5,
        saleOff: 0,
        price: '120$',
        available: true,
    },  
]